apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-eta-deploy
  labels:
    app: bankapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-eta-app
  template:
    metadata:
      labels:
        app: bankapp-eta-app
    spec:
      containers:
      - name: bankapp-eta-container
        image: pallavi2320/bankapp-eta-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-service
spec:
  type: NodePort
  selector:
    app: bankapp-eta-app
  ports:
  -   port: 80
      target port: 8081
      nodePort: 30081
