apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebappimg-deploy
  labels:
    app: mywebappimg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebappimg-app
  template:
    metadata:
      labels:
        app: mywebappimg-app
    spec:
      containers:
      - name: mywebappimg-container
        image: pallavi2320/mywebappimg
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-np-service
  labels:
    app: bankapp-eta-app
spec:
  selector:
    app: bankapp-eta-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8081
    targetPort: 8082
